const T={soldier:{hp:70,atk:12,range:22,speed:90,cost:25,size:6},tank:{hp:180,atk:28,range:30,speed:55,cost:60,size:9},air:{hp:95,atk:24,range:65,speed:145,cost:90,size:7}};const R=(a,b)=>a+Math.random()*(b-a);const D=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
export class Game{constructor(c){this.c=c;this.cv=document.querySelector("#canvas");this.x=this.cv.getContext("2d");this.u=[];this.b=[];this.money=180;this.metal=120;this.energy=100;this.score=0;this.sel=[];this.paused=false;this.last=performance.now()}
start(){this.resize();addEventListener("resize",()=>this.resize());this.b=[{x:this.w*.12,y:this.h*.5,hp:1000,o:"p"},{x:this.w*.5,y:this.h*.25,hp:1000,o:"n"},{x:this.w*.86,y:this.h*.5,hp:1000,o:"e"}];for(let i=0;i<12;i++)this.add("p",i<8?"soldier":i<11?"tank":"air",this.b[0]);for(let i=0;i<10;i++)this.add("e",i<7?"soldier":i<9?"tank":"air",this.b[2]);this.bind();requestAnimationFrame(t=>this.frame(t))}
resize(){this.w=this.cv.clientWidth;this.h=this.cv.clientHeight;this.cv.width=this.w*devicePixelRatio;this.cv.height=this.h*devicePixelRatio;this.x.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}
add(o,t,b){this.u.push({id:Math.random(),o,t,x:b.x+R(-60,60),y:b.y+R(-45,45),hp:T[t].hp,target:null,attack:null,selected:false})}
bind(){this.cv.onpointerdown=e=>{this.drag={x:e.offsetX,y:e.offsetY}};this.cv.onpointerup=e=>this.click(e);document.querySelector("#pause").onclick=()=>{this.paused=!this.paused;document.querySelector("#pause").textContent=this.paused?"▶":"Ⅱ"};document.querySelectorAll("[data-build]").forEach(q=>q.onclick=()=>this.build(q.dataset.build))}
click(e){if(!this.drag)return;const x=e.offsetX,y=e.offsetY,dx=x-this.drag.x,dy=y-this.drag.y;if(Math.hypot(dx,dy)>10){const a=Math.min(x,this.drag.x),b=Math.max(x,this.drag.x),c=Math.min(y,this.drag.y),z=Math.max(y,this.drag.y);this.sel=this.u.filter(q=>q.o==="p"&&q.x>=a&&q.x<=b&&q.y>=c&&q.y<=z)}else{const hit=this.u.find(q=>Math.hypot(q.x-x,q.y-y)<14);if(hit&&hit.o==="p")this.sel=[hit];else if(hit&&hit.o==="e")this.sel.forEach(q=>q.attack=hit.id);else this.sel.forEach((q,i)=>q.target={x:x+((i%4)-1.5)*14,y:y+(Math.floor(i/4)-1)*14})}this.u.forEach(q=>q.selected=this.sel.includes(q));this.drag=null}
build(t){const z=T[t],b=this.b[0];if(this.money<z.cost||this.metal<z.cost*.45)return;this.money-=z.cost;this.metal-=z.cost*.45;this.add("p",t,b)}
frame(now){const dt=Math.min(.04,(now-this.last)/1000);this.last=now;if(!this.paused)this.update(dt);this.draw();this.last=now;requestAnimationFrame(t=>this.frame(t))}
update(dt){this.money+=dt*8;this.metal+=dt*4;this.energy=Math.max(0,this.energy-dt*.4);for(const q of [...this.u]){const z=T[q.t],target=q.attack?this.u.find(v=>v.id===q.attack):null;if(target&&target.o!==q.o){const dd=D(q,target);if(dd<=z.range){target.hp-=z.atk*dt;if(target.hp<=0){this.score+=target.o==="e"?10:0;this.u=this.u.filter(v=>v!==target);q.attack=null}}else this.move(q,target.x,target.y,z.speed*dt)}else if(q.o==="e"){const p=this.sel[0]||this.b[0];if(p){q.attack=p.id?q.id:null;this.move(q,p.x,p.y,z.speed*.45*dt)}}else if(q.target){this.move(q,q.target.x,q.target.y,z.speed*dt);if(D(q,q.target)<5)q.target=null}}
for(const b of this.b){const h=this.u.filter(q=>q.o!==b.o&&q.o!=="n"&&D(q,b)<30).length;if(h)b.hp-=h*7*dt;if(b.hp<=0&&b.o==="e"){b.o="n";this.score+=100}if(b.hp<=0&&b.o==="p")return this.end(false)}if(!this.u.some(q=>q.o==="e"))this.end(true);document.querySelector("#resources").innerHTML=this.res("💰",this.money)+this.res("🔩",this.metal)+this.res("⚡",this.energy)+this.res("⭐",this.score)+this.res("🪖",this.u.filter(q=>q.o==="p").length)}
move(q,x,y,s){const n=Math.hypot(x-q.x,y-q.y)||1;q.x+=(x-q.x)/n*s;q.y+=(y-q.y)/n*s}
res(i,v){return '<span class="res">'+i+' <b>'+Math.floor(v)+'</b></span>'}
draw(){const c=this.x;c.clearRect(0,0,this.w,this.h);c.fillStyle="#092437";c.fillRect(0,0,this.w,this.h);c.strokeStyle="#ffffff08";for(let x=0;x<this.w;x+=70){c.beginPath();c.moveTo(x,0);c.lineTo(x,this.h);c.stroke()}for(let y=0;y<this.h;y+=70){c.beginPath();c.moveTo(0,y);c.lineTo(this.w,y);c.stroke()}for(const b of this.b){c.beginPath();c.arc(b.x,b.y,22,0,7);c.fillStyle=b.o==="p"?"#43a8ff":b.o==="e"?"#ef6666":"#d5ad3f";c.fill()}for(const q of this.u){c.beginPath();c.arc(q.x,q.y,T[q.t].size,0,7);c.fillStyle=q.o==="p"?"#43a8ff":"#ef6666";c.fill();if(q.selected){c.strokeStyle="#f2c84d";c.lineWidth=3;c.stroke()}}}
end(win){if(this.done)return;this.done=true;document.querySelector("#end").classList.remove("hidden");document.querySelector("#endTitle").textContent=win?"VICTORY":"DEFEAT";document.querySelector("#endScore").textContent="النقاط: "+this.score+" · "+this.c.name}
}